# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt/mainwindow.ui',
# licensing of 'qt/mainwindow.ui' applies.
#
# Created: Sun Aug 25 02:48:08 2019
#      by: pyside2-uic  running on PySide2 5.13.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 480)
        MainWindow.setStyleSheet("background-color: rgb(50, 50, 50);")
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.nodeInfoLabel = QtWidgets.QLabel(self.centralWidget)
        self.nodeInfoLabel.setGeometry(QtCore.QRect(440, 450, 351, 20))
        self.nodeInfoLabel.setStyleSheet("color: white")
        self.nodeInfoLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.nodeInfoLabel.setObjectName("nodeInfoLabel")
        self.closeButton = QtWidgets.QPushButton(self.centralWidget)
        self.closeButton.setGeometry(QtCore.QRect(720, 10, 64, 64))
        self.closeButton.setStyleSheet("color: transparent; border: none")
        self.closeButton.setObjectName("closeButton")
        self.titleLabel = QtWidgets.QLabel(self.centralWidget)
        self.titleLabel.setEnabled(True)
        self.titleLabel.setGeometry(QtCore.QRect(185, 10, 430, 50))
        self.titleLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.titleLabel.setStyleSheet("font-size:30pt; font-style:italic; color:white;")
        self.titleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.infoLabel = QtWidgets.QLabel(self.centralWidget)
        self.infoLabel.setGeometry(QtCore.QRect(85, 140, 630, 40))
        self.infoLabel.setStyleSheet("color:white; font-size:20px")
        self.infoLabel.setText("")
        self.infoLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.infoLabel.setObjectName("infoLabel")
        self.startButton = QtWidgets.QPushButton(self.centralWidget)
        self.startButton.setGeometry(QtCore.QRect(300, 190, 200, 100))
        self.startButton.setStyleSheet("color: white; background-color: rgba(0,255, 0, 0.75); border: none; font-size: 24px; border-radius:5px")
        self.startButton.setObjectName("startButton")
        self.selectButton = QtWidgets.QPushButton(self.centralWidget)
        self.selectButton.setGeometry(QtCore.QRect(340, 320, 120, 40))
        self.selectButton.setStyleSheet("color:black; background-color:white; border-radius: 4px")
        self.selectButton.setObjectName("selectButton")
        self.minuteLabel = QtWidgets.QLabel(self.centralWidget)
        self.minuteLabel.setGeometry(QtCore.QRect(480, 233, 60, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setWeight(50)
        font.setBold(False)
        self.minuteLabel.setFont(font)
        self.minuteLabel.setStyleSheet("color:white")
        self.minuteLabel.setObjectName("minuteLabel")
        self.hourList = QtWidgets.QListWidget(self.centralWidget)
        self.hourList.setGeometry(QtCore.QRect(260, 190, 75, 108))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setWeight(75)
        font.setBold(True)
        self.hourList.setFont(font)
        self.hourList.setStyleSheet("color:white;")
        self.hourList.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.hourList.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.hourList.setDragEnabled(False)
        self.hourList.setAlternatingRowColors(False)
        self.hourList.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.hourList.setObjectName("hourList")
        self.minuteList = QtWidgets.QListWidget(self.centralWidget)
        self.minuteList.setGeometry(QtCore.QRect(400, 190, 75, 108))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setWeight(75)
        font.setBold(True)
        self.minuteList.setFont(font)
        self.minuteList.setStyleSheet("color:white;")
        self.minuteList.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.minuteList.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.minuteList.setDragEnabled(False)
        self.minuteList.setAlternatingRowColors(False)
        self.minuteList.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.minuteList.setObjectName("minuteList")
        self.hourLabel = QtWidgets.QLabel(self.centralWidget)
        self.hourLabel.setGeometry(QtCore.QRect(340, 233, 60, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setWeight(50)
        font.setBold(False)
        self.hourLabel.setFont(font)
        self.hourLabel.setStyleSheet("color:white")
        self.hourLabel.setObjectName("hourLabel")
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        self.hourList.setCurrentRow(-1)
        self.minuteList.setCurrentRow(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.nodeInfoLabel.setText(QtWidgets.QApplication.translate("MainWindow", "Currently not connected to node", None, -1))
        self.closeButton.setText(QtWidgets.QApplication.translate("MainWindow", "X", None, -1))
        self.titleLabel.setText(QtWidgets.QApplication.translate("MainWindow", "Blockchain-Based Smart Outlet", None, -1))
        self.startButton.setText(QtWidgets.QApplication.translate("MainWindow", "Connect to\n"
"Smart Socket", None, -1))
        self.selectButton.setText(QtWidgets.QApplication.translate("MainWindow", "Select", None, -1))
        self.minuteLabel.setText(QtWidgets.QApplication.translate("MainWindow", "minutes", None, -1))
        self.hourLabel.setText(QtWidgets.QApplication.translate("MainWindow", "hours", None, -1))

